sudo: false
dist: trusty

language: node_js
node_js:
  - "11"

install:
  - npm i

script:
  - npm run build
  # todo: npm test on linux
 
jobs:
  include:
    - stage: npm deploy
      node_js: "11"
      deploy:
        provider: npm
        email: justin.m.chase@gmail.com
        api_key: $NPM_API_KEY
        skip_cleanup: true
        tag: next
        on:
          tags: true
