
target: 'with_uv'
type: exe
includes:
  - deps/{platform}/{architecture}/libuv/include
libraries:
  - deps/{platform}/{architecture}/libuv/libuv.lib
sources:
  - main.c
after_build:
  win32: bin/after_build.bat
  linux: bin/after_build.sh
  darwin:
    - bin/after_build.sh
